/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.electionsoft.improvedintent;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollProxy;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiC;
import org.appcelerator.titanium.util.Log;
import org.appcelerator.titanium.util.TiConfig;
import org.appcelerator.titanium.util.TiConvert;
import org.appcelerator.titanium.proxy.IntentProxy;


// This proxy can be created by calling Improvedintent.createIntent({action : Ti.Android.ACTION_INSERT})
// Arguments are same as Ti.Android.createIntent()
@Kroll.proxy(creatableInModule=ImprovedintentModule.class)
public class ImprovedIntentProxy extends IntentProxy
{
	// Standard Debugging variables
	private static final String LCAT = "ImprovedIntentProxy";
	private static final boolean DBG = TiConfig.LOGD;

	// Constructor
	public ImprovedIntentProxy()
	{
		super();
	}
	
	// Methods
	@Kroll.method
	public void putLongExtra(String key, Object value)
	{
		if (value instanceof Long) {
			putExtra(key, ((Long) value));
		} else if (value instanceof Integer) {
			putExtra(key, ((Integer) value).longValue());
		} else if (value instanceof Double) {
			putExtra(key, ((Double) value).longValue());
		} else if (value instanceof String) {
			putExtra(key, Long.parseLong((String) value));
		} else {
			Log.w(LCAT, "Warning unimplemented put conversion for " + value.getClass().getCanonicalName() + ", trying conversion from String to Long");
			putExtra(key, Long.parseLong(TiConvert.toString(value)));
		}
	}

}